[package]
name = "save-sloppy"
version = "0.1.0"
edition = "2021"

[dependencies]
bitcoin = { version = "0.32.5", features = [ "serde" ] }
chrono = { version = "0.4.39", features = [ "serde" ] }
serde = { version = "1.0.218", features = [ "derive" ] }
tokio = { version = "1.43.0", features = [ "full" ] }
nostr-sdk = "0.39.0"
nwc = "0.39"
reqwest = { version = "0.12.12", features=  [ "json", "stream" ] }
serde_json = "1.0.139"
futures-util = "0.3.31"
axum = "0.8.1"
anyhow = "1.0.96"
clap = "4.5.30"
rusqlite = { version = "0.32.1", features = ["bundled"] }
sqlx = { version = "0.8.3", features = [ "runtime-tokio", "tls-native-tls", "sqlite" ] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"

[dev-dependencies]
insta = { version = "1.42.1", features = ["yaml"] }
